name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approved reviews
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const reviews = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const approvedReview = reviews.data.find(review => review.state === 'APPROVED');
            if (!approvedReview) {
              core.setFailed('No approved review found.');
            } else {
              console.log('Review approved by:', approvedReview.user.login);
            }
          
      - name: Set success status if review is approved
        if: success()
        run: echo "Review has been approved, proceeding to next steps."

  sonar_analysis:
    runs-on: ubuntu-latest
    needs: review_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
        env:
          SONARQUBE_URL: https://your-sonarqube-server.com
